// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDTqW2AQfZ5cLhmx8aB1VB3_zVinhKD4w',
    appId: '1:888910023265:web:975517739b10faf9413820',
    messagingSenderId: '888910023265',
    projectId: 'bumera-fd807',
    authDomain: 'bumera-fd807.firebaseapp.com',
    storageBucket: 'bumera-fd807.appspot.com',
    measurementId: 'G-98GXP8RJW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTSibUfWMk0-DpOhXJQvbEeYklQUfAFIU',
    appId: '1:888910023265:android:4e302437cd87d385413820',
    messagingSenderId: '888910023265',
    projectId: 'bumera-fd807',
    storageBucket: 'bumera-fd807.appspot.com',
  );

}